Similarity updates
ML4GW/amplfi pull request #176
Opened 2024-11-15 15:35 UTC by EthanMarx

Updates to similarity data and model to handle new `asd` context.

2024-11-17 21:47 UTC, deepchatterjeeligo requested changes
Looks good overall. Can you add a unittest for the VICReg loss. The test can take as input samples from gaussian distribution centered at say 10 and -10 each with unit variances.

2024-11-17 21:47 UTC, deepchatterjeeligo commented on amplfi/train/losses.py
> +    loss = torch.mean(F.relu(1.0 - std))
make this `1.0` and keyword arg called `max_std`.

2024-11-18 19:43 UTC, EthanMarx commented
@deepchatterjeeligo both todos are done

2024-11-18 21:24 UTC, deepchatterjeeligo approved these changes
Thank you @EthanMarx

2024-11-18 21:26 UTC, merged